/// <reference types="Cypress" />

describe('My First Test Suite', function() 
{
    before(function() {
        cy.fixture('ConstVarbl').then(function(data) {
                this.data=data  })
      })

    it('Login ',function() {    

        cy.visit(this.data.URL)
        // login
        cy.get('.login-form > [type="text"]').type('erudt.01')
        cy.get('.login-form > .ng-pristine').type('erudt.01')
        cy.contains('Sign In').click({multiple: true})
        
        cy.get('.success').click()        
        
    })
it('Curriculam page',function() {

    // curriculam tab
    cy.get('.icon-curriculum.dash-img').click()
    cy.wait(1000)
    
    cy.get('ul li.option').contains('IIT-Class 12').click({force: true})    
    cy.get('.subject-button.Chemistry ').click()
    cy.wait(1000)
    cy.get('.subject-button.Mathematics').click()
    cy.wait(1000)
    cy.get('.subject-button.Physics').click()
    cy.wait(1000)
    // open and close chapter contents
    cy.get('.fa.fa-arrow-circle-left').click()
    cy.wait(1000)
    cy.get('.fa.fa-arrow-circle-left').click()
    cy.wait(1000)
    // refresh page
    cy.get('.fa.fa-refresh').click()
    cy.wait(1000)
    cy.get('li>div.resource-img-wrapper').click({ force: true })
    cy.wait(10000)
    // Chapter Content
    cy.get('[ng-if="show.relatedContent"] > a.ng-binding').click()
    cy.wait(2000)
    cy.get('i.fa-minus-circle').click()
    cy.wait(2000)
    // features
    cy.get('[ng-if="show.chapterFeatures"] > a.ng-binding').click()
    cy.wait(2000)
    // notes
    cy.get('[ng-if="show.notes"] > a.ng-binding').click()
    cy.wait(3000)
    cy.get('.text-center').click()
    cy.wait(3000)
    cy.get('#newNoteText').type('Creating New Notes By Videos')
    cy.wait(3000)
    cy.get('#newNotePanel > .right').click()
    cy.wait(3000)
    cy.get('#navBackBtn').click()
    //
    
})

it('Create Assignment',function() {
    //cy.get('.icon-curriculum.dash-img').click()
    //cy.wait(3000)
    cy.get('#dropdownAssignment').find('li > [ui-sref="assignmentCreate"]').click({force: true})
    cy.wait(2000)
    cy.get('#txtAssignmentName').type('MuraliMohan')
    cy.wait(2000)
    cy.get('select').eq(1).select('0').contains('Class 10')
    cy.wait(2000)
    cy.get('select').eq(2).select('1').contains('English')
    cy.wait(2000)
    cy.get('select').eq(3).select('3').contains('4 . Films And Theatre')
    cy.wait(2000)
    cy.get('ul li.option').contains('3 . Prepositions').click({force: true})
    cy.wait(2000)
    cy.get('ul li.option').contains('2 . Preposition For Time').click({force: true})
    cy.wait(2000)
    cy.get('select').eq(6).select('5').contains('30')
    cy.wait(2000)
    cy.contains('Add attachment(s)').click()
    cy.wait(3000)
    cy.contains('Create').click({force: true})
    cy.wait(3000)
    cy.get('#dropdownAssignment').find('li > [ui-sref="assignmentView"]').click({force: true})
    cy.wait(2000)
    cy.get('select').eq(1).select('0').contains('Class 10')
    cy.wait(2000)
    cy.get('select').eq(2).select('1').contains('English')
    cy.wait(2000)
    cy.get('select').eq(3).select('3').contains('4 . Films And Theatre')
    cy.wait(2000)
    cy.get('select').eq(4).select('0').contains('Created Date')
    cy.wait(2000)
    cy.get('.fa.fa-calendar').click({ multiple: true })
    cy.wait(2000)
    cy.get('.fa.fa-calendar').click({ multiple: true })
    cy.wait(2000)
    cy.get('[ng-click="showPushedAssignments()"]').click()
    cy.wait(2000)
})
it('Create Activity',function() {
    cy.get('#dropdownActivity').find('li > [ui-sref="activityCreate"]').click({force: true})
    cy.wait(2000)
    cy.get('#txtAssignmentName').type('MuraliMohan')
    cy.wait(2000)
    cy.get('select').eq(1).select('0').contains('Class 10')
    cy.wait(2000)
    cy.get('select').eq(2).select('1').contains('English')
    cy.wait(2000)
    cy.get('select').eq(3).select('3').contains('4 . Films And Theatre')
    cy.wait(2000)
    cy.get('ul li.option').contains('3 . Prepositions').click({force: true})
    cy.wait(2000)
    cy.get('ul li.option').contains('2 . Preposition For Time').click({force: true})
    cy.wait(2000)
    cy.get('.cke_contents').type('Description is mandatory')
    cy.wait(2000)
    cy.get('[ng-click="saveAndPush()"]').click()
    cy.wait(3000)
    cy.get('#dropdownActivity').find('li > [ui-sref="activityView"]').click({force: true})
    cy.get('select').eq(1).select('0').contains('Class 10')
    cy.wait(2000)
    cy.get('select').eq(2).select('1').contains('English')
    cy.wait(2000)
    cy.get('select').eq(3).select('3').contains('4 . Films And Theatre')
    cy.wait(2000)
    cy.get('select').eq(4).select('0').contains('Start Date')
    cy.wait(2000)
    cy.get('.fa.fa-calendar').click({ multiple: true })
    cy.wait(2000)
    cy.get('.fa.fa-calendar').click({ multiple: true })
    cy.wait(2000)
    cy.get('[ng-click="showUnPushedAssignments()"]').click()
    cy.wait(2000)
})
it('Create Assessment',function() {
    cy.get('#dropdownAssessment').find('[ui-sref="assessmentCreate"]').click({force: true})
    cy.wait(2000)
    /*cy.get('#assessmentName').type('MuraliMohan')
    cy.wait(2000)
    cy.get('select').eq(1).select('0').contains('English')
    cy.wait(2000)
    cy.get('select').eq(2).select('0').contains('Class 10')
    cy.wait(2000)
    cy.get('select').eq(3).select('0').contains('Biology')
    cy.wait(2000)
    cy.get('select').eq(4).select('1').contains('Medium')
    cy.wait(2000)
    cy.get('select').eq(5).select('0').contains('5 mins')
    cy.wait(2000)
    cy.get('select').eq(6).select('0').contains('5')
    cy.wait(2000) */
    cy.get('#dropdownAssessment').find('li > [ui-sref="assessmentList"]').click({force: true})
    cy.wait(2000)
    cy.get('select').eq(1).select('0').contains('Class 10')
    cy.wait(2000)
    cy.get('select').eq(2).select('0').contains('Biology')
    cy.wait(2000)
    cy.get('select').eq(3).select('1').contains('2 . Respiration-the Energy Releasing System (శ్వాసక్రియ-శక్తి ఉత్పాదక వ్యవస్థ)')
    cy.wait(2000)
    cy.get('select').eq(4).select('0').contains('Created Date')
    cy.wait(2000)
    cy.get('.fa.fa-calendar').click({ multiple: true })
    cy.wait(2000)
    cy.get('.fa.fa-calendar').click({ multiple: true })
    cy.wait(2000)
    cy.get('[ng-show="show.unpushed"]').click()
    cy.wait(2000)
})
it('EntranceExamPractise',function() {
    cy.get('a.ng-scope > .icon-competitive').click()
    cy.wait(2000)
    cy.get('.Physics').click()
    cy.wait(2000)
    cy.get('.Mathematics').click()
    cy.wait(2000)
    cy.get('select').eq(2).select('2385').contains('Matrices')
    cy.wait(2000)
    cy.get('[title="Types Of Matrices"]').click()
    cy.contains('>').click()// next pdf page
    cy.wait(2000)
    cy.contains('+').click()
    cy.wait(2000)
    cy.contains('Fit Page').click()
    cy.wait(2000)
    cy.get('#navBackBtn').click()
})
    it('Logout test',function() {
        //cy.wait(5000)
        cy.get('.fa.fa-power-off').click()

    })


})